# Generated by Django 4.2.7 on 2023-12-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='precio',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='edad',
            field=models.IntegerField(max_length=5),
        ),
    ]
