# Generated by Django 4.2.7 on 2023-12-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_actividad_descripcion_alter_actividad_precio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
        migrations.DeleteModel(
            name='Asistencia',
        ),
    ]
