# Generated by Django 4.2.7 on 2023-12-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actividad', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
